### ISSUE TITLE
Getting "RuntimeError - No input found for jasnyfile:" with this gem.

### ISSUE THREAD

**Issue by blimey85** [turbod/simple_form_jasny_fileupload#1]
I have a project that already had everything installed. I then added your gem and updated my form to use the input as you specified, changing it to match the field I have.

`= f.input :avatar, as: :jasnyfile, label: false`

Immediately ran into a problem. It seems like the gem isn't being picked up by my app. SimpleForm isn't seeing the new input definition.

`RuntimeError - No input found for jasnyfile:`

I then tried to manually install the stuff from your gem and that mostly worked but I get this:

`NoMethodError - undefined method `remove_avatar' for #<User:0x007f96ecc30c00>:`

I'm using Rails 5.0.3. Is there something I need to update for this to work with Rails 5 or am I just missing a step somewhere?

**Comment by turbod** [comment]
I think you don't installed the carrierwave gem or you not configured properly the uploader.
The avatar is the name of your attribute, please check your attribute name, maybe your attribute name is different.

**Comment by blimey85** [comment]
Ok, I found the issue. I had everything setup correctly on my end, however there's a missing step in the directions. In the initializers folder you need to include a line to tell SimpleForm to map the new input that is created by your gem.

```
/config/initializers/simple_form.rb
SimpleForm::FormBuilder.map_type :jasnyfile, to: SimpleForm::Inputs::JasnyfileInput
```
Once I added this the error went away and everything is working. Just as a note, I found the solution via an issue posted to a similar module here: https://github.com/andreapavoni/simple_form_fancy_uploads/issues/15
